name: Publish juancobo6-marco-polo to PyPI

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: latest

      - name: Install build dependencies
        run: uv pip install --system --upgrade setuptools setuptools_scm

      - name: Build juancobo6-marco-polo package
        run: |
          cd juancobo6_marco_polo
          uv build --sdist --wheel

      - name: Publish juancobo6-marco-polo to PyPI
        run: |
          cd juancobo6_marco_polo
          uv publish --token ${{ secrets.PYPI_API_TOKEN }}
