name: Publish juancobo6-marco-polo-timeseries to PyPI

on:
  push:
    tags:
      - 'ts*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          version: latest

      - name: Install build dependencies
        run: uv pip install --system --upgrade setuptools setuptools_scm

      - name: Build juancobo6-marco-polo-timeseries package
        run: uv build --sdist --wheel juancobo6_marco_polo_timeseries

      - name: Publish juancobo6-marco-polo-timeseries to PyPI
        run: uv publish --token ${{ secrets.PYPI_API_TOKEN }} juancobo6_marco_polo_timeseries/dist/*
